modules/backend/controllers/SliderController.php
<?php

namespace app\modules\backend\controllers;

use app\modules\backend\forms\SliderForm;
use Yii;
use app\models\Slider;
use app\modules\backend\models\SliderSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\base\Model;
use app\modules\backend\forms\PhotosForm;

/**
 * SliderController implements the CRUD actions for Slider model.
 */
class SliderController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Slider models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SliderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Slider model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($name)
    {
	    $models = $this->findModelByName($name);
	    $sliderName = $this->findSliderName($name);

        return $this->render('view', [
            'model' =>$models,
	        'sliderName' => $sliderName,
        ]);
    }

    /**
     * Creates a new Slider model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Slider();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['update', 'name' => $model->name]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Slider model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $name
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($name)
    {
        $models = $this->findModelByName($name);
        foreach ($models as $model){
	        $model->imageFile = new PhotosForm();
	        $model->imageFile->id = $model->id;
        }
	    //$imageFile = new PhotosForm();
	    $newSlide = new Slider();
	    $newSlide->imageFile = new PhotosForm();

		$sliderName = new SliderForm($name);
        if( Yii::$app->request->isPost){
			if($sliderName->load(Yii::$app->request->post()) && $sliderName->validate() && (int)$sliderName->changeTitle === 1){
				Slider::updateAll(['name'=>$sliderName->name],['name'=>$name]);
				return $this->redirect(['update', 'name' => $sliderName->name]);
			}

	        if (Model::loadMultiple($models, Yii::$app->request->post()) && Model::validateMultiple($models)) {
		        foreach ($models as $model) {
		        	//TODO need check or set try catch if uploaded images not all slides
			        if ($model->imageFile->validate() && $model->imageFile->files) {
			        	if(isset($model->imageFile->files[0]) && !is_null($model->imageFile->files[0])){
					        $model->setPhoto($model->imageFile->files[0]);
				        }
			        }
			        $model->save();
		        }
	        }
	        if ($newSlide->load(Yii::$app->request->post()) && $newSlide->validate()) {
		        $newSlide->name = $name;
		        if ($newSlide->imageFile->validate() && $newSlide->imageFile->files) {
			        if ( isset( $newSlide->imageFile->files[0] ) && ! is_null( $newSlide->imageFile->files[0] ) ) {
				        $newSlide->setPhoto( $newSlide->imageFile->files[0] );
			        }
		        }
		        $newSlide->save();
	        }
	        return $this->redirect(['update', 'name' => $name]);
        }

        return $this->render('update', [
            'slides' => $models,
	        'newSlide' => $newSlide,
	        'sliderName' => $sliderName,
        ]);
    }

    /**
     * Deletes an existing Slider model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($name)
    {
	    Slider::deleteAll(['name' => $name]);
        return $this->redirect(['index']);
    }

	/**
	 * Deletes an existing Slider model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 * @param integer $id
	 * @return mixed
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	public function actionDeleteSlide($id)
	{
		$slider = $this->findModel($id);
		if(!is_null($slider)){
			$name = $slider->name;
			$slider->delete();
			return $this->redirect(['update', 'name' => $name]);
		}
		return $this->redirect(['index']);
	}
    /**
     * Finds the Slider model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Slider the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Slider::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
	/**
	 * Finds the Slider model based on its name value.
	 * If the model is not found, a 404 HTTP exception will be thrown.
	 * @param integer $id
	 * @return Slider the loaded model
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	protected function findModelByName($name)
	{
		if (($model = Slider::find()->where(['name' => $name])->orderBy('id')->indexBy('id')->all()) !== []) {
			return $model;
		}

		throw new NotFoundHttpException('The requested page does not exist.');
	}

	/**
	 * Finds the Slider nam4 model
	 * If the model is not found, a 404 HTTP exception will be thrown.
	 * @param integer $id
	 * @return Slider the loaded model
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	protected function findSliderName($name)
	{
		if (($model = Slider::find()->select(['name'])->where(['name' => $name])->limit(1)->one()) !== null) {
			return $model;
		}

		throw new NotFoundHttpException('The requested page does not exist.');
	}
}

modules/backend/views/slider/_form-create.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $slides app\models\Slider */
/* @var $newSlide app\models\Slider */
/* @var $sliderName app\modules\backend\forms\SliderForm  */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="slider-form">
	<?php $form = ActiveForm::begin(); ?>
    <div class="box box-default">
        <div class="box-header with-border">
            Основное
        </div>
        <div class="box-body">
	        <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-default">
                <div class="box-header with-border">Новый Слайд</div>
                <div class="box-body">

				    <?= $form->field($model, 'comment')->textInput(['maxlength' => true]) ?>

				    <?= $form->field($model, 'photo')->textInput(['maxlength' => true]) ?>

				    <?= $form->field($model, 'link')->textInput(['maxlength' => true]) ?>

                </div>
            </div>
        </div>
    </div>
        <div class="row">
            <div class="col-xs-12">
                <div class="form-group">
                    <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
                </div>
            </div>
        </div>


    <?php ActiveForm::end(); ?>

</div>

modules/backend/views/slider/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\file\FileInput;
use mihaildev\ckeditor\CKEditor;
use mihaildev\elfinder\ElFinder;

/* @var $this yii\web\View */
/* @var $slides app\models\Slider */
/* @var $newSlide app\models\Slider */
/* @var $sliderName app\modules\backend\forms\SliderForm  */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="slider-form">
	<?php $formTitle = ActiveForm::begin(); ?>
    <div class="box box-default">
        <div class="box-header with-border">
            Основное
        </div>
        <div class="box-body">
	        <?=Html::activeHiddenInput($sliderName, 'changeTitle', ['value' => 1]); ?>
	        <?= $formTitle->field($sliderName, 'name')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="box-body">
            <div class="form-group">
                <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
            </div>
        </div>
    </div>
	<?php ActiveForm::end(); ?>

	<?php $form = ActiveForm::begin([
		'options' => ['enctype'=>'multipart/form-data']
	]);
	?>

    <div class="row">
	    <?php
        $i=0;
        foreach ($slides as $index => $model):
            $i++;
        ?>

            <div class="col-md-6 col-xs-12">
                <div class="box box-default">
                    <div class="box-header with-border">Слайд <?= $i ?>
                        <div class="box-tools pull-right">
	                        <?= Html::a('<span aria-hidden="true">&times;</span>', ['slider/delete-slide', 'id' => $model->id], [
		                        'class' => 'btn btn-danger',
		                        'data' => [
			                        'confirm' => 'Уверены, что хотите удалить слайдер?',
			                        'method' => 'post',
		                        ],
	                        ]) ?>
                        </div>
                    </div>
                    <div class="box-body">
                            <?=Html::activeHiddenInput($model, '[' . $index . ']id', ['value' => $model->id]); ?>

                            <?= $form->field($model, '[' . $index . ']comment')->widget(CKEditor::className(),[
	                            'editorOptions' => ElFinder::ckeditorOptions('elfinder',[
	                                    'preset' => 'basic',
	                                    'clientOptions' => [
		                                    'config.allowedContent' => true,
		                                    'allowedContent' => true,
	                                    ],
                                ]),
                            ]) ?>

                            <?php if ($model->photo): ?>
	                            <?= Html::a(Html::img($model->getThumbFileUrl('photo', 'thumb'),['style'=>'height:230px']), $model->getUploadedFileUrl('photo'), [
		                            'class' => 'thumbnail',
		                            'target' => '_blank'
	                            ]) ?>
                            <?php endif; ?>
                            <?php echo $form->field($model->imageFile, 'files[' . $model->id . ']')->label(false)->widget(FileInput::classname(), [
                                'options' => ['multiple' => true],
                                'language' => 'ru',
                                'pluginOptions' => ['previewFileType' => 'any']
                            ]); ?>

                            <?= $form->field($model, '[' . $index . ']link')->textInput(['maxlength' => true]) ?>
                    </div>
                </div>
            </div>

        <?php endforeach; ?>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <div class="form-group">
				<?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
            </div>
        </div>
    </div>
	    <?php ActiveForm::end(); ?>
	    <?php $form = ActiveForm::begin([
		    'options' => ['enctype'=>'multipart/form-data']
	    ]);
	    ?>
    <div class="row">
        <div class="col-md-6 col-xs-12">
            <div class="box box-default">
                <div class="box-header with-border">Новый Слайд</div>
                <div class="box-body">
				    <?= $form->field($newSlide, 'comment')->widget(CKEditor::className(),[
					    'editorOptions' => ElFinder::ckeditorOptions('elfinder',[
						    'preset' => 'basic',
						    'clientOptions' => [
							    'config.allowedContent' => true,
							    'allowedContent' => true,
						    ],
					    ]),
				    ]) ?>
				    <?php echo $form->field($newSlide->imageFile, 'files')->label(false)->widget(FileInput::classname(), [
					    'options' => ['multiple' => true],
					    'language' => 'ru',
					    'pluginOptions' => ['previewFileType' => 'any']
				    ]); ?>
				    <?= $form->field($newSlide, 'link')->textInput(['maxlength' => true]) ?>

                </div>
            </div>
        </div>
    </div>
        <div class="row">
            <div class="col-xs-12">
                <div class="form-group">
                    <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
                </div>
            </div>
        </div>


    <?php ActiveForm::end(); ?>

</div>

modules/backend/views/slider/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\backend\models\SliderSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="slider-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?php // $form->field($model, 'id') ?>

    <?php // $form->field($model, 'comment') ?>

    <?php // $form->field($model, 'photo') ?>

    <?php // $form->field($model, 'link') ?>

    <?= $form->field($model, 'name') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/backend/views/slider/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Slider */

$this->title = 'Создать слайдер';
$this->params['breadcrumbs'][] = ['label' => 'Слайдер', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="slider-create">
    <div class="box-body">
        <?= $this->render('_form-create', [
            'model' => $model,
        ]) ?>
    </div>
</div>

modules/backend/views/slider/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel app\modules\backend\models\SliderSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Слайдеры';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="slider-index">

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Создать слайдер', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <div class="box">
        <div class="box-body">
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'columns' => [
                    ['class' => 'yii\grid\SerialColumn'],
                    'name',
	                ['class' => 'yii\grid\ActionColumn',
	                 'template'=>'{view}{update}{delete}',
	                 'buttons'=>[
		                 'view' => function ($url, $model) {
			                 return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', Url::to(['slider/view', 'name' => $model->name]), [
				                 'title' => 'Просмотреть',
			                 ]);
		                 },
		                 'update' => function ($url, $model) {
			                 return Html::a('<span class="glyphicon glyphicon-pencil"></span>', Url::to(['slider/update', 'name' => $model->name]), [
				                 'title' => 'Редактировать',
			                 ]);
		                 },
		                 'delete' => function ($url, $model) {

			                 return Html::a('<span class="glyphicon glyphicon-trash"></span>', ['slider/delete', 'name' => $model->name], [
				                 'class' => '',
				                 'title' => 'Удалить',
				                 'data' => [
					                 'confirm' => 'Уверены, что хотите удалить слайдер?',
					                 'method' => 'post',
				                 ],
			                 ]);
		                 },
	                 ]
	                ],
                ],
            ]); ?>
        </div>
    </div>
</div>

modules/backend/views/slider/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $slides app\models\Slider */
/* @var $newSlide app\models\Slider */
/* @var $sliderName app\modules\backend\forms\SliderForm */

$this->title = 'Редактировать Слайдер: '.$sliderName->name;
$this->params['breadcrumbs'][] = ['label' => 'Слайдеры', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $sliderName->name, 'url' => ['view', 'name' => $sliderName->name]];
$this->params['breadcrumbs'][] = 'Редактирование';
?>
<div class="slider-update">
    <div class="box-body">
        <?= $this->render('_form', [
            'slides' => $slides,
            'sliderName' => $sliderName,
            'newSlide' => $newSlide,
        ]) ?>
    </div>
</div>

modules/backend/views/slider/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Slider */
/* @var $sliderName app\models\Slider */


$this->title = $sliderName->name;
$this->params['breadcrumbs'][] = ['label' => 'Слайдеры', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="slider-view">

    <p>
        <?= Html::a('Редактировать', ['update', 'name' => $sliderName->name], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['delete', 'name' => $sliderName->name], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Уверены, что хотите удалить слайдер?',
                'method' => 'post',
            ],
        ]) ?>
    </p>
    <div class="box">
        <div class="box-body">
            <?= DetailView::widget([
                'model' => $sliderName,
                'attributes' => [
                    'name',
                ],
            ]) ?>
        </div>
    </div>
</div>